'use client'
import { useState, useRef, useCallback } from 'react'
import { Phone, AlertTriangle, CheckCircle, Send, Loader2, Mic, MicOff, FileText, RefreshCw } from 'lucide-react'
import RiskBadge, { ConfidenceGauge } from '@/components/RiskBadge'
import ErrorBoundary from '@/components/ErrorBoundary'
import { ResultSkeleton } from '@/components/Skeletons'

const EXAMPLES = [
  "I am calling from CBI headquarters. We have found your Aadhaar linked to a money laundering case. You are under digital arrest. Do not tell anyone or we will send police to your home immediately.",
  "This is TRAI. Your mobile number will be disconnected in 2 hours due to illegal activities. Press 1 to speak with cyber crime officer.",
  "Your FedEx parcel contains drugs. Narcotics department has a warrant. Stay on video call for verification or you will be arrested.",
]

interface Analysis {
  riskLevel: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'SAFE'
  scamType: string
  confidence: number
  indicators: string[]
  impersonatedAgency: string
  redFlags: string[]
  recommendation: string
  mhaAlert: string
}

interface HistoryEntry {
  id: string
  text: string
  result: Analysis
  timestamp: string
}

function getHistory(): HistoryEntry[] {
  if (typeof window === 'undefined') return []
  try {
    return JSON.parse(localStorage.getItem('safenet-scam-history') || '[]')
  } catch { return [] }
}

function saveHistory(entry: HistoryEntry) {
  const history = getHistory()
  history.unshift(entry)
  localStorage.setItem('safenet-scam-history', JSON.stringify(history.slice(0, 50)))
}

function generateComplaintDraft(result: Analysis, transcript: string): string {
  const date = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
  return `CYBERCRIME COMPLAINT DRAFT
Generated by SafeNet India · ${date}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TO: Officer-in-Charge, Cyber Crime Police Station
SUBJECT: Report of ${result.scamType}

BRIEF FACTS:
The complainant received a communication containing the following content:

"${transcript.slice(0, 500)}"

AI ANALYSIS RESULTS:
• Risk Level: ${result.riskLevel}
• Scam Type: ${result.scamType}
• Confidence: ${result.confidence}%
${result.impersonatedAgency ? `• Impersonated Agency: ${result.impersonatedAgency}` : ''}

RED FLAGS DETECTED:
${result.redFlags.map((f, i) => `${i + 1}. ${f}`).join('\n')}

INDICATORS:
${result.indicators.map((i) => `• ${i}`).join('\n')}

REQUESTED ACTION:
${result.recommendation}

PRAY FOR:
1. Registration of FIR under relevant sections of IT Act, 2000 and BNS
2. Immediate blocking of identified phone numbers/accounts
3. Investigation into the fraud network

Filed through: SafeNet India AI Platform
(Note: This is an AI-generated draft. Please review and submit to cybercrime.gov.in or nearest cyber cell.)`
}

export default function ScamDetectorPage() {
  const [text, setText] = useState('')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<Analysis | null>(null)
  const [error, setError] = useState('')
  const [isRecording, setIsRecording] = useState(false)
  const [transcript, setTranscript] = useState('')
  const [history, setHistory] = useState<HistoryEntry[]>([])
  const [showHistory, setShowHistory] = useState(false)
  const [showComplaint, setShowComplaint] = useState(false)
  const [retryCount, setRetryCount] = useState(0)
  const recognitionRef = useRef<any>(null)

  const loadHistory = useCallback(() => {
    setHistory(getHistory())
    setShowHistory(!showHistory)
  }, [showHistory])

  function toggleVoiceInput() {
    if (!('webkitSpeechRecognition' in window) && !('SpeechRecognition' in window)) {
      setError('Speech recognition is not supported in this browser. Try Chrome.')
      return
    }

    if (isRecording) {
      recognitionRef.current?.stop()
      setIsRecording(false)
      return
    }

    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition
    const recognition = new SpeechRecognition()
    recognitionRef.current = recognition
    recognition.continuous = true
    recognition.interimResults = true
    recognition.lang = 'en-IN'

    recognition.onresult = (event: any) => {
      let finalTranscript = ''
      for (let i = 0; i < event.results.length; i++) {
        if (event.results[i].isFinal) {
          finalTranscript += event.results[i][0].transcript + ' '
        }
      }
      if (finalTranscript) {
        setText(prev => prev + finalTranscript)
        setTranscript(prev => prev + finalTranscript)
      }
    }

    recognition.onerror = () => {
      setIsRecording(false)
    }

    recognition.onend = () => {
      setIsRecording(false)
    }

    recognition.start()
    setIsRecording(true)
  }

  async function analyse(attempt = 0) {
    if (!text.trim()) return
    setLoading(true)
    setError('')
    setResult(null)
    try {
      const res = await fetch('/api/scam-detect', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text }),
      })
      const data = await res.json()
      if (data.error) throw new Error(data.error)
      setResult(data)
      setRetryCount(0)

      const entry: HistoryEntry = {
        id: Date.now().toString(),
        text: text.slice(0, 200),
        result: data,
        timestamp: new Date().toISOString(),
      }
      saveHistory(entry)
      setHistory(getHistory())
    } catch (e: any) {
      if (attempt < 2) {
        setRetryCount(attempt + 1)
        await new Promise(r => setTimeout(r, 1000 * (attempt + 1)))
        return analyse(attempt + 1)
      }
      setError(e.message || 'Analysis failed after retries. Please try again.')
      setRetryCount(0)
    } finally {
      setLoading(false)
    }
  }

  function downloadComplaint() {
    if (!result) return
    const draft = generateComplaintDraft(result, text)
    const blob = new Blob([draft], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `safenet-complaint-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <ErrorBoundary>
      <div className="pt-24 min-h-screen px-6 pb-16">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="mb-10">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 bg-accent/10 border border-accent/30 rounded-lg flex items-center justify-center">
                <Phone size={18} className="text-accent" />
              </div>
              <div>
                <p className="mono text-accent text-xs">MODULE 01</p>
                <h1 className="text-2xl font-display font-bold text-bright">Digital Arrest Scam Detector</h1>
              </div>
            </div>
            <p className="text-muted text-sm leading-relaxed max-w-2xl">
              Paste the call script, record live audio, or describe the conversation.
              Our AI cross-references 47 known scam patterns and known government impersonation scripts.
            </p>
          </div>

          {/* Input */}
          <div className="border border-border bg-panel rounded-xl p-6 mb-4">
            <label className="mono text-xs text-muted mb-3 block">CALL TRANSCRIPT / MESSAGE CONTENT</label>
            <textarea
              value={text}
              onChange={e => setText(e.target.value)}
              rows={6}
              placeholder="Paste the suspicious message or call script here, or use voice input..."
              className="w-full bg-void border border-border rounded-lg p-4 text-bright text-sm placeholder:text-muted resize-none focus:outline-none focus:border-accent/50 transition-colors"
            />
            <div className="flex items-center justify-between mt-4 flex-wrap gap-3">
              <div className="flex gap-2 flex-wrap">
                {EXAMPLES.map((ex, i) => (
                  <button
                    key={i}
                    onClick={() => setText(ex)}
                    className="mono text-xs text-muted hover:text-accent border border-border hover:border-accent/30 px-3 py-1.5 rounded-lg transition-all"
                  >
                    Example {i + 1}
                  </button>
                ))}
                <button
                  onClick={toggleVoiceInput}
                  className={`mono text-xs border px-3 py-1.5 rounded-lg transition-all flex items-center gap-1.5 ${
                    isRecording
                      ? 'text-white bg-accent border-accent animate-pulse'
                      : 'text-muted hover:text-accent border-border hover:border-accent/30'
                  }`}
                >
                  {isRecording ? <MicOff size={12} /> : <Mic size={12} />}
                  {isRecording ? 'Stop Recording' : 'Voice Input'}
                </button>
                <button
                  onClick={loadHistory}
                  className="mono text-xs text-muted hover:text-accent border border-border hover:border-accent/30 px-3 py-1.5 rounded-lg transition-all flex items-center gap-1.5"
                >
                  <FileText size={12} /> History ({getHistory().length})
                </button>
              </div>
              <button
                onClick={() => analyse()}
                disabled={loading || !text.trim()}
                className="flex items-center gap-2 bg-accent text-white px-5 py-2.5 rounded-lg font-semibold text-sm hover:bg-accent/90 disabled:opacity-40 disabled:cursor-not-allowed transition-all"
              >
                {loading ? <Loader2 size={14} className="animate-spin" /> : <Send size={14} />}
                {loading ? `Analysing${retryCount > 0 ? ` (retry ${retryCount})` : ''}...` : 'Analyse Threat'}
              </button>
            </div>
          </div>

          {error && (
            <div className="border border-accent/30 bg-accent/5 rounded-xl p-4 text-accent text-sm flex items-center justify-between">
              <span>{error}</span>
              <button onClick={() => analyse()} className="text-accent hover:underline flex items-center gap-1 text-xs">
                <RefreshCw size={12} /> Retry
              </button>
            </div>
          )}

          {loading && <ResultSkeleton />}

          {/* Result */}
          {result && !loading && (
            <div className="border border-border bg-panel rounded-xl overflow-hidden">
              {/* Risk Header */}
              <div className={`p-6 border-b border-border ${result.riskLevel === 'CRITICAL' || result.riskLevel === 'HIGH' ? 'bg-accent/5' : result.riskLevel === 'SAFE' ? 'bg-safe/5' : 'bg-warn/5'}`}>
                <div className="flex items-start justify-between">
                  <div>
                    <div className="flex items-center gap-3 mb-2">
                      {result.riskLevel === 'SAFE'
                        ? <CheckCircle size={20} className="text-safe" />
                        : <AlertTriangle size={20} className="text-accent threat-pulse" />
                      }
                      <RiskBadge level={result.riskLevel} />
                    </div>
                    <h2 className="text-xl font-bold text-bright">{result.scamType}</h2>
                    {result.impersonatedAgency && (
                      <p className="text-muted text-sm mt-1">Impersonating: <span className="text-warn">{result.impersonatedAgency}</span></p>
                    )}
                  </div>
                  <ConfidenceGauge value={result.confidence} level={result.riskLevel} />
                </div>
              </div>

              <div className="p-6 grid md:grid-cols-2 gap-6">
                {/* Red Flags */}
                <div>
                  <p className="mono text-xs text-muted mb-3">DETECTED RED FLAGS</p>
                  <ul className="space-y-2">
                    {result.redFlags.map((flag, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-bright">
                        <span className="text-accent mt-0.5">⚠</span> {flag}
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Indicators */}
                <div>
                  <p className="mono text-xs text-muted mb-3">SCAM PATTERN INDICATORS</p>
                  <ul className="space-y-2">
                    {result.indicators.map((ind, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-muted">
                        <span className="text-border mt-0.5">→</span> {ind}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Recommendation */}
              <div className="px-6 pb-4">
                <div className="border border-safe/20 bg-safe/5 rounded-lg p-4">
                  <p className="mono text-xs text-safe mb-2">RECOMMENDED ACTION</p>
                  <p className="text-bright text-sm">{result.recommendation}</p>
                </div>
              </div>

              {/* File Complaint */}
              {(result.riskLevel === 'CRITICAL' || result.riskLevel === 'HIGH') && (
                <div className="px-6 pb-4">
                  <div className="border border-accent/20 bg-accent/5 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <p className="mono text-xs text-accent">FILE A COMPLAINT</p>
                      <button
                        onClick={downloadComplaint}
                        className="flex items-center gap-1.5 text-xs text-accent font-medium hover:underline mono"
                      >
                        <FileText size={12} /> Download Draft
                      </button>
                    </div>
                    <p className="text-muted text-xs">
                      Pre-filled complaint draft for cybercrime.gov.in or nearest cyber cell.
                      Review and submit with your details.
                    </p>
                  </div>
                </div>
              )}

              {/* MHA Alert */}
              {result.mhaAlert && (
                <div className="px-6 pb-6">
                  <p className="mono text-xs text-muted mb-2">DRAFT MHA ALERT</p>
                  <div className="bg-void border border-border rounded-lg p-4 mono text-xs text-muted whitespace-pre-wrap">
                    {result.mhaAlert}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* History Panel */}
          {showHistory && history.length > 0 && (
            <div className="mt-6 border border-border bg-panel rounded-xl p-6">
              <p className="mono text-xs text-muted mb-4">RECENT ANALYSES</p>
              <div className="space-y-3 max-h-64 overflow-y-auto">
                {history.map((entry) => (
                  <div
                    key={entry.id}
                    className="flex items-center justify-between py-2 border-b border-border last:border-0 cursor-pointer hover:bg-void/50 rounded px-2 transition-colors"
                    onClick={() => { setText(entry.text); setResult(entry.result); setShowHistory(false) }}
                  >
                    <div className="flex-1 min-w-0">
                      <p className="text-bright text-sm truncate">{entry.text}</p>
                      <p className="text-muted text-xs mono">{new Date(entry.timestamp).toLocaleString()}</p>
                    </div>
                    <div className="ml-3 shrink-0">
                      <RiskBadge level={entry.result.riskLevel} />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </ErrorBoundary>
  )
}
