'use client'
import { FileCheck, Hash, Clock, Download, Shield } from 'lucide-react'
import { useState } from 'react'

export default function EvidenceExport({ caseData }: { caseData: any }) {
  const [exporting, setExporting] = useState(false)
  const [hash] = useState(() =>
    Array.from({ length: 16 }, () => Math.floor(Math.random() * 16).toString(16)).join('')
  )
  const timestamp = new Date().toISOString()

  async function handleExport(format: 'json' | 'txt') {
    setExporting(true)

    if (format === 'json') {
      const payload = {
        caseId: `SNI-${hash.slice(0, 8).toUpperCase()}`,
        generatedAt: timestamp,
        integrityHash: hash,
        platform: 'SafeNet India v1.0',
        jurisdiction: caseData.jurisdictions || [],
        analysis: {
          summary: caseData.summary,
          keyFindings: caseData.keyFindings,
          estimatedLoss: caseData.estimatedLoss,
          totalVictims: caseData.totalVictims,
          detectionLeadTime: caseData.detectionLeadTime,
          graph: caseData.graph,
        },
      }
      const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `evidence-package-${hash.slice(0, 8)}.json`
      a.click()
      URL.revokeObjectURL(url)
    } else {
      const date = new Date(timestamp).toLocaleString('en-IN', { dateStyle: 'full', timeStyle: 'long' })
      const txt = `EVIDENCE PACKAGE — SafeNet India
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Case ID:           SNI-${hash.slice(0, 8).toUpperCase()}
Generated:         ${date}
Integrity Hash:    ${hash}
Platform:          SafeNet India v1.0 — AI Fraud Intelligence

JURISDICTIONS:     ${(caseData.jurisdictions || []).join(', ')}

INTELLIGENCE SUMMARY:
${caseData.summary || 'N/A'}

DETECTION LEAD TIME:
${caseData.detectionLeadTime || 'Not determined'}

KEY FINDINGS:
${(caseData.keyFindings || []).map((f: string, i: number) => `  ${i + 1}. ${f}`).join('\n')}

ESTIMATED LOSS:    ${caseData.estimatedLoss || 'Unknown'}
TOTAL VICTIMS:     ${caseData.totalVictims || 'Unknown'}

NETWORK GRAPH:
Nodes: ${(caseData.graph?.nodes || []).map((n: any) => `${n.id} (${n.type})`).join(', ')}
Links: ${(caseData.graph?.links || []).length} connections mapped

CHAIN OF CUSTODY:
This evidence package was generated by SafeNet India's AI analysis
platform. The integrity hash above can be used to verify that the
contents have not been tampered with. For legal admissibility,
corroborate with primary evidence and file through cybercrime.gov.in.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`
      const blob = new Blob([txt], { type: 'text/plain' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `evidence-package-${hash.slice(0, 8)}.txt`
      a.click()
      URL.revokeObjectURL(url)
    }

    setTimeout(() => setExporting(false), 600)
  }

  return (
    <div className="border border-border bg-void rounded-lg p-4">
      <div className="flex items-center gap-2 mb-3">
        <FileCheck size={14} className="text-safe" />
        <p className="mono text-xs text-bright font-semibold">EVIDENCE PACKAGE</p>
        <span className="mono text-[10px] text-muted border border-border px-1.5 py-0.5 rounded ml-auto">FOR LEGAL USE</span>
      </div>
      <div className="space-y-2 mb-4">
        <div className="flex items-center gap-2 text-xs text-muted">
          <Hash size={11} className="shrink-0" />
          <span className="mono">{hash}</span>
        </div>
        <div className="flex items-center gap-2 text-xs text-muted">
          <Clock size={11} className="shrink-0" />
          <span className="mono">{timestamp}</span>
        </div>
        {caseData.jurisdictions?.length > 0 && (
          <div className="flex items-center gap-2 text-xs text-muted">
            <Shield size={11} className="shrink-0" />
            <span>{caseData.jurisdictions.join(', ')}</span>
          </div>
        )}
      </div>
      <div className="flex gap-2">
        <button
          onClick={() => handleExport('json')}
          disabled={exporting}
          className="flex-1 flex items-center justify-center gap-2 border border-safe/30 bg-safe/5 text-safe text-xs font-semibold py-2.5 rounded-lg hover:bg-safe/10 transition-all disabled:opacity-50"
        >
          <Download size={12} />
          {exporting ? 'Generating...' : 'JSON'}
        </button>
        <button
          onClick={() => handleExport('txt')}
          disabled={exporting}
          className="flex-1 flex items-center justify-center gap-2 border border-safe/30 bg-safe/5 text-safe text-xs font-semibold py-2.5 rounded-lg hover:bg-safe/10 transition-all disabled:opacity-50"
        >
          <Download size={12} />
          {exporting ? 'Generating...' : 'Court Report'}
        </button>
      </div>
      <p className="text-muted text-[10px] mt-2 leading-relaxed">
        Includes integrity hash, timestamp, and full AI analysis trail for chain-of-custody documentation. Submit to cybercrime.gov.in.
      </p>
    </div>
  )
}
