'use client'
import { useState, useRef, useCallback } from 'react'
import { Banknote, Upload, Loader2, CheckCircle, XCircle, Camera, RefreshCw, FileText } from 'lucide-react'
import RiskBadge, { ConfidenceGauge } from '@/components/RiskBadge'
import ErrorBoundary from '@/components/ErrorBoundary'
import { ResultSkeleton } from '@/components/Skeletons'

interface ScanResult {
  verdict: 'GENUINE' | 'COUNTERFEIT' | 'SUSPICIOUS'
  confidence: number
  denomination: string
  checks: { name: string; passed: boolean; detail: string }[]
  summary: string
  action: string
}

interface ImageSlot {
  file: File | null
  preview: string | null
  label: string
}

function getHistory(): { id: string; denomination: string; verdict: string; confidence: number; timestamp: string }[] {
  if (typeof window === 'undefined') return []
  try {
    return JSON.parse(localStorage.getItem('safenet-currency-history') || '[]')
  } catch { return [] }
}

function saveHistory(entry: { id: string; denomination: string; verdict: string; confidence: number; timestamp: string }) {
  const history = getHistory()
  history.unshift(entry)
  localStorage.setItem('safenet-currency-history', JSON.stringify(history.slice(0, 30)))
}

export default function CurrencyScannerPage() {
  const [images, setImages] = useState<ImageSlot[]>([
    { file: null, preview: null, label: 'Front Side' },
    { file: null, preview: null, label: 'Back Side' },
  ])
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<ScanResult | null>(null)
  const [error, setError] = useState('')
  const [retryCount, setRetryCount] = useState(0)
  const [history, setHistory] = useState(getHistory())
  const [showHistory, setShowHistory] = useState(false)
  const inputRefs = useRef<(HTMLInputElement | null)[]>([])

  function handleFile(f: File, index: number) {
    const reader = new FileReader()
    reader.onload = (e) => {
      setImages(prev => prev.map((img, i) =>
        i === index ? { ...img, file: f, preview: e.target?.result as string } : img
      ))
    }
    reader.readAsDataURL(f)
    setResult(null)
    setError('')
  }

  function addImageSlot() {
    setImages(prev => [...prev, { file: null, preview: null, label: `Image ${prev.length + 1}` }])
  }

  async function scan(attempt = 0) {
    const validImages = images.filter(i => i.preview)
    if (!validImages.length) return
    setLoading(true)
    setError('')
    try {
      const imagePayloads = validImages.map(img => ({
        imageBase64: img.preview!.split(',')[1],
        mimeType: img.file?.type || 'image/jpeg',
        label: img.label,
      }))

      const res = await fetch('/api/currency-scan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ images: imagePayloads, single: false }),
      })
      const data = await res.json()
      if (data.error) throw new Error(data.error)
      setResult(data)
      setRetryCount(0)

      saveHistory({
        id: Date.now().toString(),
        denomination: data.denomination,
        verdict: data.verdict,
        confidence: data.confidence,
        timestamp: new Date().toISOString(),
      })
      setHistory(getHistory())
    } catch (e: any) {
      if (attempt < 2) {
        setRetryCount(attempt + 1)
        await new Promise(r => setTimeout(r, 1000 * (attempt + 1)))
        return scan(attempt + 1)
      }
      setError(e.message || 'Scan failed after retries. Please try again.')
      setRetryCount(0)
    } finally {
      setLoading(false)
    }
  }

  function downloadReport() {
    if (!result) return
    const date = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
    const report = `CURRENCY SECURITY ANALYSIS REPORT
SafeNet India · ${date}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DENOMINATION: ${result.denomination}
VERDICT: ${result.verdict}
CONFIDENCE: ${result.confidence}%

SECURITY CHECKS:
${result.checks.map(c => `${c.passed ? '✓' : '✗'} ${c.name}: ${c.detail}`).join('\n')}

SUMMARY: ${result.summary}

ACTION: ${result.action}

Generated by SafeNet India AI Platform`
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `safenet-currency-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const verdictColor = { GENUINE: 'text-safe', COUNTERFEIT: 'text-accent', SUSPICIOUS: 'text-warn' }
  const hasImages = images.some(i => i.preview)

  return (
    <ErrorBoundary>
      <div className="pt-24 min-h-screen px-6 pb-16">
        <div className="max-w-4xl mx-auto">
          <div className="mb-10">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 bg-warn/10 border border-warn/30 rounded-lg flex items-center justify-center">
                <Banknote size={18} className="text-warn" />
              </div>
              <div>
                <p className="mono text-warn text-xs">MODULE 02</p>
                <h1 className="text-2xl font-display font-bold text-bright">Counterfeit Currency Scanner</h1>
              </div>
            </div>
            <p className="text-muted text-sm leading-relaxed max-w-2xl">
              Upload front + back photos of any Indian currency note for comprehensive FICN detection.
              Gemini Vision analyses security features, microprint patterns, and serial number validity.
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-6">
            {/* Upload */}
            <div>
              <div className="space-y-3">
                {images.map((img, idx) => (
                  <div
                    key={idx}
                    onClick={() => inputRefs.current[idx]?.click()}
                    onDragOver={e => e.preventDefault()}
                    onDrop={e => { e.preventDefault(); const f = e.dataTransfer.files[0]; if (f) handleFile(f, idx) }}
                    className="border-2 border-dashed border-border hover:border-warn/40 bg-panel rounded-xl p-4 flex items-center gap-4 cursor-pointer transition-all"
                  >
                    {img.preview ? (
                      <img src={img.preview} alt={img.label} className="w-20 h-20 object-contain rounded-lg bg-void" />
                    ) : (
                      <div className="w-20 h-20 rounded-lg bg-warn/10 border border-warn/20 flex items-center justify-center shrink-0">
                        <Camera size={20} className="text-warn" />
                      </div>
                    )}
                    <div>
                      <p className="text-bright text-sm font-medium">{img.label}</p>
                      <p className="text-muted text-xs mt-0.5">{img.preview ? 'Click to replace' : 'Drop image or click to browse'}</p>
                    </div>
                    <input
                      ref={el => { inputRefs.current[idx] = el }}
                      type="file"
                      accept="image/*"
                      className="hidden"
                      onChange={e => { const f = e.target.files?.[0]; if (f) handleFile(f, idx) }}
                    />
                  </div>
                ))}
              </div>

              <div className="flex gap-2 mt-3">
                <button
                  onClick={addImageSlot}
                  className="mono text-xs text-muted hover:text-warn border border-border hover:border-warn/30 px-3 py-1.5 rounded-lg transition-all"
                >
                  + Add Image
                </button>
                <button
                  onClick={() => { setHistory(getHistory()); setShowHistory(!showHistory) }}
                  className="mono text-xs text-muted hover:text-warn border border-border hover:border-warn/30 px-3 py-1.5 rounded-lg transition-all flex items-center gap-1"
                >
                  <FileText size={12} /> History
                </button>
              </div>

              {hasImages && (
                <button
                  onClick={() => scan()}
                  disabled={loading}
                  className="w-full mt-4 flex items-center justify-center gap-2 bg-warn text-black px-5 py-3 rounded-lg font-semibold hover:bg-warn/90 disabled:opacity-40 transition-all"
                >
                  {loading ? <Loader2 size={16} className="animate-spin" /> : <Upload size={16} />}
                  {loading ? `Scanning${retryCount > 0 ? ` (retry ${retryCount})` : ''}...` : 'Run Security Analysis'}
                </button>
              )}

              {error && (
                <div className="mt-4 border border-accent/30 bg-accent/5 rounded-lg p-3 text-accent text-sm flex items-center justify-between">
                  <span>{error}</span>
                  <button onClick={() => scan()} className="text-accent hover:underline flex items-center gap-1 text-xs">
                    <RefreshCw size={12} /> Retry
                  </button>
                </div>
              )}
            </div>

            {/* Result */}
            <div>
              {loading ? (
                <ResultSkeleton />
              ) : result ? (
                <div className="border border-border bg-panel rounded-xl overflow-hidden h-full">
                  <div className={`p-5 border-b border-border ${result.verdict === 'GENUINE' ? 'bg-safe/5' : result.verdict === 'COUNTERFEIT' ? 'bg-accent/5' : 'bg-warn/5'}`}>
                    <div className="flex items-start justify-between">
                      <div>
                        <div className="flex items-center gap-3 mb-1">
                          {result.verdict === 'GENUINE'
                            ? <CheckCircle size={20} className="text-safe" />
                            : <XCircle size={20} className="text-accent" />
                          }
                          <span className={`text-2xl font-bold mono ${verdictColor[result.verdict]}`}>
                            {result.verdict}
                          </span>
                        </div>
                        <p className="text-muted text-sm">{result.denomination}</p>
                      </div>
                      <ConfidenceGauge
                        value={result.confidence}
                        level={result.verdict === 'GENUINE' ? 'SAFE' : result.verdict === 'COUNTERFEIT' ? 'CRITICAL' : 'MEDIUM'}
                      />
                    </div>
                  </div>

                  <div className="p-5 space-y-3">
                    <p className="mono text-xs text-muted mb-2">SECURITY CHECKS</p>
                    {result.checks.map((check) => (
                      <div key={check.name} className="flex items-start gap-3">
                        <span className={check.passed ? 'text-safe mt-0.5' : 'text-accent mt-0.5'}>
                          {check.passed ? '✓' : '✗'}
                        </span>
                        <div>
                          <p className="text-bright text-sm font-medium">{check.name}</p>
                          <p className="text-muted text-xs">{check.detail}</p>
                        </div>
                      </div>
                    ))}
                  </div>

                  <div className="px-5 pb-5 space-y-3">
                    <div className="border border-border bg-void rounded-lg p-3">
                      <p className="mono text-xs text-muted mb-1">ACTION REQUIRED</p>
                      <p className="text-bright text-sm">{result.action}</p>
                    </div>
                    <button
                      onClick={downloadReport}
                      className="w-full flex items-center justify-center gap-2 border border-border text-bright px-4 py-2 rounded-lg font-medium text-sm hover:border-warn/40 hover:bg-panel transition-all"
                    >
                      <FileText size={14} /> Download Report
                    </button>
                  </div>
                </div>
              ) : (
                <div className="border border-dashed border-border bg-panel/50 rounded-xl h-full min-h-[280px] flex items-center justify-center">
                  <p className="text-muted text-sm text-center">Upload note images to see<br />the security analysis here</p>
                </div>
              )}
            </div>
          </div>

          {/* History Panel */}
          {showHistory && history.length > 0 && (
            <div className="mt-6 border border-border bg-panel rounded-xl p-6">
              <p className="mono text-xs text-muted mb-4">RECENT SCANS</p>
              <div className="space-y-2 max-h-48 overflow-y-auto">
                {history.map((entry) => (
                  <div key={entry.id} className="flex items-center justify-between py-2 border-b border-border last:border-0">
                    <div>
                      <span className="text-bright text-sm">{entry.denomination}</span>
                      <span className="text-muted text-xs ml-2 mono">{new Date(entry.timestamp).toLocaleString()}</span>
                    </div>
                    <span className={`mono text-xs font-bold ${entry.verdict === 'GENUINE' ? 'text-safe' : entry.verdict === 'COUNTERFEIT' ? 'text-accent' : 'text-warn'}`}>
                      {entry.verdict} · {entry.confidence}%
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </ErrorBoundary>
  )
}
